name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'  # Thay đổi theo phiên bản Node.js mà bạn cần
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
      
      - name: Build project
        run: npm run build  # Thay đổi nếu bạn có lệnh build khác
      
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Thêm lệnh deploy của bạn ở đây
